name: Build Kernel Driver

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the driver using MSBuild
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        msbuild KernelDriver.vcxproj /p:Configuration=Release /p:Platform=x64

    - name: Upload driver artifact
      uses: actions/upload-artifact@v4
      with:
        name: driver-binary
        path: x64/Release/KernelDriver.sys
