name: Build Kernel Driver

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Add msbuild to path
      uses: microsoft/setup-msbuild@v1.3

    - name: Build the driver
      run: msbuild KernelDriver.vcxproj /p:Configuration=Release /p:Platform=x64
      
    - name: Upload driver artifact
      uses: actions/upload-artifact@v4
      with:
        name: driver-binary
        path: x64/Release/KernelDriver.sys
